name:                queuing-simulation
version:             0.1.0.0
github:              "EsGeh/virtualq_codingchallenge"
license:             BSD3
author:              "EsGeh"
maintainer:          "SamuelGfroerer@googlemail.com"
copyright:           "2018 EsGeh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/EsGeh/virtualq_codingchallenge#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -fno-warn-tabs 

executables:
  queuing-simulation-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-tabs 
    dependencies:
    - queuing-simulation

tests:
  queuing-simulation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-tabs 
    dependencies:
    - queuing-simulation
